version: '3'
services:
  web:
    build: .
    volumes:
      - .:/opt/app
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - codeplay_data:/var/lib/postgresql/data
volumes:
  codeplay_data:

